#ifndef CAPTURE_GPU_ERRORS
#define CAPTURE_GPU_ERRORS

#include <cuda_runtime.h>
#include "exceptions.h"

/*
 * Capture and throw any GPU error state generated by the kernel.
 *
 *      gpuErrorFlag - this is the GPU memory object.  We need to
 *                     copy this to the hostErrorFlag for evaluation.
 *
 *      If CUDA has an error state, throw CudaException(err) but if
 *      hostErrorFlag has any other error, throw the appropriate
 *      exception.
 */
void captureGpuErrors(int *gpuErrorFlag);

#endif